### PR TITLE
Adding documentation for creating single server and multi server

### PR DESCRIPTION
**Pull request by italovalcy**
This pull request adds the documentation to creating single server and multiple servers

### CODE REVIEW

**Review by mcevik0 — APPROVED** [review]

**Comment by sajith** [comment]
@italovalcy I made #24 to address a warning from Sphinx.  It should also fix this rendering issue:

image

Please merge #24 onto this branch before merging. Thanks!

**Comment by italovalcy** [comment]
> @italovalcy I made #24 to address a warning from Sphinx. It should also fix this rendering issue:
> 
> image
> 
> Please merge #24 onto this branch before merging. Thanks!

Hi @sajith thanks a lot for the help here, my friend! Very much appreciated. I just merged PR 24 into this branch.  Amazing to have your contribution here!

**Review by sajith — APPROVED** [review]
LGTM!

To be clear, I have not actually tested the instructions. But very glad we have it now, and I'm sure we'll be able to fix any gaps when following them.

**Comment by italovalcy** [comment]
Thanks a lot for you review @sajith and @mcevik0 !

**Pull request merged**
